# Generated by Django 3.0 on 2019-12-11 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=200, verbose_name='轮播标题')),
                ('image', models.ImageField(help_text='（图片格式：png，图片尺寸：400*300px）', upload_to='banner/', verbose_name='轮播图片')),
                ('link_url', models.URLField(verbose_name='链接地址')),
                ('sort_number', models.IntegerField(default=1, verbose_name='排序号')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_code', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='栏目代码')),
                ('category_name', models.CharField(max_length=50, verbose_name='栏目名称')),
                ('category_type', models.IntegerField(choices=[(1, '栏目'), (2, '文章'), (3, '页面'), (4, '链接')], default=1, verbose_name='栏目类型')),
                ('link_url', models.URLField(blank=True, max_length=100, verbose_name='链接地址')),
                ('link_target', models.CharField(blank=True, choices=[('_self', '本窗口'), ('_blank', '新窗口'), ('_parent', '父窗口'), ('_top', '顶层窗口')], max_length=10, null=True, verbose_name='打开方式')),
                ('sort_number', models.IntegerField(default=100, verbose_name='排序号')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('parent', models.ForeignKey(blank=True, limit_choices_to=models.Q(category_type=1), null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.Category', verbose_name='上级栏目')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='推荐位描述')),
            ],
            options={
                'verbose_name': '推荐位',
                'verbose_name_plural': '推荐位',
            },
        ),
        migrations.CreateModel(
            name='SinglePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', mdeditor.fields.MDTextField()),
                ('keywords', models.CharField(blank=True, max_length=200, null=True, verbose_name='关键字')),
                ('intro', models.CharField(blank=True, max_length=2000, null=True, verbose_name='简介')),
                ('views', models.IntegerField(default=0, verbose_name='浏览量')),
                ('category', models.ForeignKey(default=None, limit_choices_to=models.Q(category_type=3), on_delete=django.db.models.deletion.CASCADE, to='base.Category', verbose_name='栏目')),
            ],
            options={
                'verbose_name': '页面',
                'verbose_name_plural': '页面',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(default=None, editable=False, null=True, verbose_name='删除时间')),
                ('info_date', models.DateField(default=django.utils.timezone.now, verbose_name='日期')),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name='作者')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', mdeditor.fields.MDTextField()),
                ('keywords', models.CharField(blank=True, max_length=500, null=True, verbose_name='关键字')),
                ('intro', models.CharField(blank=True, max_length=2000, null=True, verbose_name='简介')),
                ('cover', models.ImageField(blank=True, help_text='（图片格式：png，图片尺寸：400*300px）', null=True, upload_to='cover/%Y/%m/%d/', verbose_name='封面')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否启用')),
                ('views', models.IntegerField(default=0, verbose_name='浏览量')),
                ('category', models.ForeignKey(limit_choices_to=models.Q(category_type=2), on_delete=django.db.models.deletion.DO_NOTHING, to='base.Category', verbose_name='栏目')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('position', models.ManyToManyField(blank=True, null=True, to='base.Position', verbose_name='推荐位')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
    ]
